services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: zenkar-backend
    restart: always
    ports:
      - "3001:3000" # Shifted to 3001 to free up 3000 for Frontend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/order_book?schema=public"
    networks:
      - zenkar-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: zenkar-frontend
    restart: always
    ports:
      - "3000:80" # Nginx expects Frontend on 3000
    depends_on:
      - backend
    networks:
      - zenkar-network

  db:
    image: postgres:15-alpine
    container_name: zenkar-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_book
    ports:
      - "5435:5432"
    volumes:
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - zenkar-network

networks:
  zenkar-network:
    driver: bridge
