services:
  backend:
    build:
      context: ../../
      dockerfile: backend/Dockerfile
    container_name: zenkar-backend-prod
    restart: always
    ports:
      - "3001:3000" # Shifted to 3001
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/order_book?schema=public"
    networks:
      - zenkar-network

  frontend:
    build:
      context: ../../
      dockerfile: frontend/Dockerfile
    container_name: zenkar-frontend-prod
    restart: always
    ports:
      - "5174:5173" # Nginx expects Frontend on 5174 (Mapped to 5173)
    depends_on:
      - backend
    networks:
      - zenkar-network

  db:
    image: postgres:15-alpine
    container_name: zenkar-db-prod
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_book
    ports:
      - "5433:5432"
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
    networks:
      - zenkar-network

networks:
  zenkar-network:
    driver: bridge
