services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - ../../minio_data_demo:/data

  backend:
    build:
      context: ../../
      dockerfile: backend/Dockerfile
    image: zenkar-backend:staging
    container_name: zenkar-backend-demo
    restart: always
    ports:
      - "3000:3000" # Demo Backend on 3000 (Internal & Host)
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/zenkar_db_demo?schema=public"
    networks:
      - zenkar-network-demo

  frontend:
    build:
      context: ../../
      dockerfile: frontend/Dockerfile
    image: zenkar-frontend:staging
    container_name: zenkar-frontend-demo
    restart: always
    ports:
      - "5173:5173" # Demo Frontend on 5173 (Internal & Host)
    depends_on:
      - backend
    networks:
      - zenkar-network-demo

  db:
    image: postgres:15-alpine
    container_name: zenkar-db-demo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zenkar_db_demo
    volumes:
      - ../../pgdata_demo:/var/lib/postgresql/data # Isolated Data Volume
    networks:
      - zenkar-network-demo
    ports:
      - "5432:5432" # Exposed on 5432

networks:
  zenkar-network-demo:
    driver: bridge
